### ISSUE TITLE
Support for high order functions

### ISSUE THREAD

**Issue by mhsdesign** [nicojs/typed-inject#51]
i set up my project using higher-order functions for the dependencies similar to: https://medium.com/geekculture/dependency-injection-in-javascript-2d2e4ad9df49

```ts
// application/ports.ts
export interface Logger {
  log(msg: string): void;
}

// application/fooFunction.ts
interface Dependencies {
  logger: Logger;
}

export const makeFooFunction({ logger }: Dependencies ) = (foo: string) => {
   // foo bar
   logger.log("bung" + foo)
}
```

i was wondering if this higher-order pattern could technically also be implemented / be used for di with this project (if yes maybe i can build it myself but idk)

(fx. by setting `makeFooFunction.inject = ['logger']`)

**Comment by mhsdesign** [comment]
uups sorry there is already https://github.com/nicojs/typed-inject#injectorinjectfunctionfn-injectablefunction

(i find this beeing to far down in the docs -> its not teasered like class di at the top)

**Comment by nicojs** [comment]
So I guess this issue can be closed?

**Comment by mhsdesign** [comment]
jup sorry i forgot;)
